# Generated by Django 2.0 on 2018-08-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180809_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reader_num',
            field=models.IntegerField(default=0),
        ),
    ]
