# Generated by Django 2.0 on 2018-08-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_reader_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='reader_num',
            new_name='readed_num',
        ),
    ]
